### ISSUE TITLE
일별, 주별, 월별 버튼 생성 및 시간축 업데이트

### ISSUE THREAD

**Issue by jik0090** [linewalks/timeline#19]
**개요 및 요청사항**
일별, 주별, 월별 버튼 생성 및 시간축 업데이트

**결과물**
일별, 주별, 월별 버튼 생성 및 시간축 업데이트

**완료 기준**
- [x]  PR Review @paulsoh  
- [x]  PR Review @hurcy

**Comment by hurcy** [comment]
@jik0090 현재 PR 내용으로 보면, `시간축 줌 기능` 을 `시간축 업데이트`로 바꿔야할것 같습니다.
