### ISSUE TITLE
문자열 길이에 따른 label이 잘리는 현상 해결

### ISSUE THREAD

**Issue by jik0090** [linewalks/timeline#42]
**개요 및 요청사항**
문자열 길이에 따른 label이 잘리는 현상 해결
**결과물**
문자열 길이에 따른 label이 잘리는 현상 해결

**완료 기준**
- [x]  PR Review @paulsoh  
- [x]  PR Review @hurcy

**Comment by hurcy** [comment]
다양하게 테스트해보시고, 최대 문자열수를 알려주세요. 그에 맞게 데이터를 제공하겠습니다.

**Comment by jik0090** [comment]
@hurcy 현재 최대 문자열수는 11개인데, 변수명중 제일긴 문자열개수를 알수있을까요?

**Comment by hurcy** [comment]
의약품군 이름중에 가장 긴게 17자이고요. 약물군이라고 prefix를 붙이면 32자 되네요.
e.g. `Prescription - immunosuppressant`
넉넉잡아 40자로 할까요?
random sample data에 라벨 길이도 랜덤하게 생성하도록 추가해야겠네요.

**Comment by jik0090** [comment]
@hurcy 이 이슈는 디자인 시안적용과함께 하겠습니다.
