### ISSUE TITLE
Timeline 과 Line Chart Merge

### ISSUE THREAD

**Issue by jik0090** [linewalks/timeline#47]
**개요 및 요청사항**
![timeline+line](https://user-images.githubusercontent.com/37281455/61422921-c0dd9f80-a948-11e9-9086-65712c1e5282.png)

**결과물**
Timeline 과 Line Chart Merge

**완료 기준**
- [ ]  PR Review @toyjhlee 
- [ ]  PR Review @hurcy

**Comment by hurcy** [comment]
예시 데이터 ([patientTimeline.zip](https://github.com/linewalks/timeline/files/3405131/patientTimeline.zip))
- 라인차트: patientTimelienMaceRisk.js
- 타임라인: patientTimeline.js
